### ISSUE TITLE
Playlist code fails for multiple accounts

### ISSUE THREAD

**Issue by erikaburbach** [10up/brightcove-video-connect#73] opened 2016-12-08 12:41 UTC
Playlist embeds for non-default account fails.

When embedding a playlist, it looks like a player is selected by default, always from the default account, even if the playlist is in another account. 

(A player list isn't displayed when embedding, and the shortcode doesn't include a player ID as with the video shortcode.) 

1. If I choose a playlist to embed from the default account, the posted player functions.
2. If I embed a playlist from the non-default account, the posted player fails.
3. If I change the default account at the plugin level, the existing previously failing post now works, and the working post breaks.

what's the criteria for which player is auto-chosen from the default account?

**Comment by oscarssanchez** [comment] 2023-06-20 19:49
Closing since I cannot reproduce this (likely it has been fixed at this point)

**Closed by oscarssanchez** 2023-06-20 19:49 UTC
