### ISSUE TITLE
Plugin fails with "Error "fetch players" permission missing showing when validating the credentials"

### ISSUE THREAD

**Issue by harniman** [10up/brightcove-video-connect#76] opened 2017-01-12 10:50 UTC
The plugin uses the VIP function `vip_safe_wp_remote_get` if available which is used to safely fetch the players from Brightcove, when the function is executed from the local environment it returns false since the local environment is not safe. This produces the error and the account details are not validated and stored in the WordPress. The fix for that is to comment the particular function and use the WordPress function instead.

**Comment by sudar** [comment] 2017-05-03 04:56
@harniman 

`vip_safe_wp_remote_get` is a wrapper to `wp_remote_get` that adds some additional logic if the code is running in VIP environment.

> when the function is executed from the local environment it returns false since the local environment is not safe

Can you explain this a bit more? Also how is your local enviroment setup? Are you using vip quickstart?

**Comment by dariomannu** [comment] 2017-05-03 14:42
Hi @sudar, we're not using VIP quickstart.

So far we've just got as far as monkey-patching the below code on local environments to force the path through `wp_remote_get`.

```
if ( function_exists( 'vip_safe_wp_remote_get' ) ) {
	$request = vip_safe_wp_remote_get( $url, '', 3, 3, 20, $args );
} else {
	$request = wp_remote_get( $url, $args );
}
```

Does that make sense?

**Comment by sudar** [comment] 2017-05-03 14:48
@dariomannu 

I am not sure if I still fully understand the issue.

The `vip_safe_wp_remote_get` function only exists in VIP environment. In your local if you are not using VIP Quickstart then the `if ( function_exists( 'vip_safe_wp_remote_get' ) ) {` condition at 
 https://github.com/10up/brightcove-video-connect/blob/develop/includes/api/class-bc-api.php#L105 would fail since `vip_safe_wp_remote_get` is not present and the call to `wp_remote_get` would be made right?

Or are you including VIP specific functions through a mu-plugin?

**Comment by dariomannu** [comment] 2017-05-03 23:24
I just tried going through the whole journey again, and I was actually surprised that everything worked first time on a local setup.

At the end of the day, the bit of code above seems to make sense the way it is. Do we remember the exact steps to reproduce the issue? I might have missed something this time...

**Comment by sudar** [comment] 2017-05-04 02:06
@dariomannu 

Not a problem. Sometimes it is easier to talk through code ;)

I am going to close this for now. Feel free to re-open if you are facing this issue again or have additional details.

**Closed by sudar** 2017-05-04 02:06 UTC

**Comment by kelvinwongg** [comment] 2017-05-24 09:20
Hi @sudar and @harniman , think i got this same problem when using the WordPress plugin. I tested it in another environment with the same credentials, it works fine. Is that caused by a connection problem between BC API and the client?

**Comment by sudar** [comment] 2017-05-25 13:58
@kelvinwongg 

Yeah it might be possible that the plugin was not able to fetch the players because of some network issue.

Please let me know if you are able to replicate it consistently.
