### ISSUE TITLE
Brightcove Playlists search functionality is not working properly

### ISSUE THREAD

**Issue by sudip-md** [10up/brightcove-video-connect#258] opened 2022-03-17 08:28 UTC
### Describe the bug

Brightcove Playlists search functionality should work properly, If user search a keyword then match keyword should be rendered first.

### Steps to Reproduce

1. Login to Admin
2. Go to Brightcove 
3. Click on Playlist
4. Search playlist

### Screenshots, screen recording, code snippet

Screenshot - https://www.screencast.com/t/49IdlrqxUf

### Environment information

Device Macbook
Browser : Chrome

### WordPress information

Plugin Version : 2.5.1
Wp version - 5.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment] 2022-03-17 13:10
I could not reproduce @sudip-10up ,

I did notice the spinner is not doing appearing in your screencast which hints a JavaScript issue. Are you testing with latest develop or ?

**Comment by oscarssanchez** [comment] 2023-06-16 00:07
Closing as could not reproduce.

**Closed by oscarssanchez** 2023-06-16 00:07 UTC
Labels: bug, reporter feedback
