### ISSUE TITLE
Add new label is not working

### ISSUE THREAD

**Issue by sudip-md** [10up/brightcove-video-connect#257] opened 2022-03-17 08:21 UTC
### Describe the bug

User is not able to add label

### Steps to Reproduce

1. Go to Brightcove 
2. Click on Label
3. Add New Label

### Screenshots, screen recording, code snippet

ScreenShot - https://www.screencast.com/t/4unaHwCOBn

### Environment information

- Device Macbook
- Browser : Chrome

### WordPress information

Plugin Version : 2.5.1
Wp version - 5.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment] 2022-03-17 13:03
Hi @sudip-10up ,

I just tried this and it works for me. Can you confirm you have the labels feature activated? Brightcove needs to activate the feature for you before you can add new labels.

**Comment by oscarssanchez** [comment] 2023-06-16 00:07
Closing as could not reproduce.

**Closed by oscarssanchez** 2023-06-16 00:07 UTC
Labels: bug, reporter feedback
